AllCops:
  Exclude:
    - '*.gemspec'

Layout/EndOfLine:
  EnforcedStyle: lf

Style/RedundantReturn:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
